### PR TITLE
update koe.py

### PR DESCRIPTION
**Pull request by sarthak-gp**
updated the where method

### CODE REVIEW

**Comment by sarthak-gp** [comment]
for /news

**Comment by albertopastormr** [comment]
Thanks for your pull request, we really appreciate it, but I don't see what you're trying to do with your code.
The command '/where' returns the location of the association, did you try to return useful links in that method?

**Comment by sarthak-gp** [comment]
Yes
I thought the \where method was used to give the useful data science
related news. Is it not so?

Sarthak Gopal Panda
Mobile- +91 7008977306
               +91 7682824206

**Comment by albertopastormr** [comment]
The command /news does what you explained, which have been already implemented.

**Pull request closed without merging**
